### ISSUE TITLE
Создать новую вкладку, где будут динамически рисоваться каналы

### ISSUE THREAD

**Issue by artempelyovin** [artempelyovin/FluxViewer#2]
Нужно создать НОВУЮ вкладку в программе с двумя кнопками:
- Добавить канал (добавляет +1 окно)
- Удалить канал (удаляет последнее окно)

Должно быть похоже на это:

![изображение](https://github.com/user-attachments/assets/27f16b53-65ff-4c76-a209-fd93b795bf8a)

Только:
- Графики не рисуем, просто обычное окно
- Окна расставлять не надо (просто добавлять/удалять)
- Рассчитывать размеры окон тоже не надо
- Вкладка должна представлять из себя отдельный класс по аналогии с текущими и располагаться `FluxViewer.WindowsClient`:
 
![изображение](https://github.com/user-attachments/assets/f28cf277-dade-4229-abb0-bc5c21646b3d)

**Comment by DaniilFedorino** [comment]
1

**Comment by Quallcomgit** [comment]
Взял

**Comment by artempelyovin** [comment]
Закрыто в https://github.com/artempelyovin/FluxViewer/pull/13
