### ISSUE TITLE
Написать класс, который хранит текущее состояние каналов

### ISSUE THREAD

**Issue by artempelyovin** [artempelyovin/FluxViewer#6]
Класс должен хранить следующее текущее состояние:
- Информацию о каждом канале (ID, название, единицы измерения, тип, отображение, сохранение)
- Информацию об общем канале (какие конкретно каналы на нём отображать)

Также класс должен уметь быть воссоздан из настроек (файл `settings,xml`). 
Предлагаю сделать это при помощи static метода

И также класс должен уметь сохранять своё состояние в настройки (файл `settings.xml`)

Если работать с `.xml` будет не удобно, можно использовать другой формат файла (JSON, txt, ...)

И ещё класс должен иметь методы по добавлению/удалению каналов

**Comment by AlekseyAlalykin** [comment]
Взял

**Comment by artempelyovin** [comment]
Закрыто в https://github.com/artempelyovin/FluxViewer/pull/15
